#!/bin/bash

SCRIPT_DIR="${BASH_SOURCE[0]}";
if ([ -h "${SCRIPT_DIR}" ]) then
  while([ -h "${SCRIPT_DIR}" ]) do SCRIPT_DIR=`readlink "${SCRIPT_DIR}"`; done
fi
pushd . > /dev/null
cd `dirname ${SCRIPT_DIR}` > /dev/null
SCRIPT_DIR=`pwd`;
popd  > /dev/null

CONFIG_FILE=${CONFIG_FILE:-$SCRIPT_DIR/config}

error() {
    CODE="$1"
    shift
    while [ -n "$1" ] ; do
        echo "$1" 1>&2
        shift
    done
    exit $CODE
}

# load some more defaults
[[ -z "$SEND" ]] && SEND=true

EXT_IP4_SERVICE="ip.appspot.com"
EXT_IP4_OPTS="-4"
EXT_IP4_EXEC="curl"

source $CONFIG_FILE || error 1 "Could not load configuration file at:" "$CONFIG_FILE"
# TODO Check config values (e.g. KEYFILE)

EXT_IP4_CMD="$EXT_IP4_EXEC $EXT_IP4_OPTS $EXT_IP4_SERVICE >/dev/null"

INT_IP4_CMD="$SCRIPT_DIR/ip4"
IP6_CMD="$SCRIPT_DIR/ip6"

if [[ "$USE_INTERNAL_IPV4" != "true" ]]; then
    IP4_CMD="$EXT_IP4_CMD"
    [ -x "$EXT_IP4_EXEC" ] || which "$EXT_IP4_EXEC">/dev/null || error 2 "Could not find $EXT_IP4_EXEC!"
else
    IP4_CMD="$INT_IP4_CMD"
    [ -x "$IP4_CMD" ] || error 3 "Could not find the ip4 executable:" "$IP4_CMD"
fi

# Check that those tools exist and are executables
[ -x "$IP6_CMD" ] || error 4 "Could not find the ip6 executable:" "$IP6_CMD"

IP4="$($IP4_CMD | head -n1)"
IP6="$($IP6_CMD | head -n1)"

# TODO validate input

UPDFILE=$(tempfile --prefix "ddns-" --suffix -$(date -I))
touch "$UPDFILE" || error 5 "Failed to create temporary file:" "$UPDFILE"

# TODO trap remove file

cat > "$UPDFILE" <<EOF1
server $ZONE
zone $ZONE.
update delete $HOST.$ZONE. A
update delete $HOST.$ZONE. AAAA
EOF1

[ -z "${IP4}" ] || echo "update add $HOST.$ZONE. 60 A $IP4" >> "$UPDFILE"
[ -z "${IP6}" ] || echo "update add $HOST.$ZONE. 60 AAAA $IP6" >> "$UPDFILE"

echo "show" >> "$UPDFILE"

if [ "true" != "$SEND" ]; then
    echo "Not sending: \"SEND\" is set to false." 1>&2
else
    echo "send" >> "${UPDFILE}"
fi

cat "$UPDFILE" | nsupdate -k "$KEYFILE"
rm "$UPDFILE"

