#!/bin/bash
cd "$( dirname "${BASH_SOURCE[0]}" )"

source config || export SUCCESS=false

if [[ $SUCCESS == false ]];then
  echo "Error: no config found"
  exit 1
fi

IP4CMD=./ip4
IP6CMD=./ip6

which $IP4CMD >/dev/null && IP4="`${IP4CMD} | head -n1`"
which $IP6CMD >/dev/null && IP6="`${IP6CMD} | head -n1`"
#TODO validate input

UPDFILE=`tempfile --prefix "ddns-" --suffix -$(date -I)`
touch "${UPDFILE}" || exit 1
#TODO trap remove file

cat > "${UPDFILE}" <<EOF1
server $ZONE
zone $ZONE.
update delete $HOST.$ZONE. A
update delete $HOST.$ZONE. AAAA
EOF1

[[ -z "${IP4}" ]] || echo "update add $HOST.$ZONE. 60 A ${IP4}" >> "${UPDFILE}"
[[ -z "${IP6}" ]] || echo "update add $HOST.$ZONE. 60 AAAA ${IP6}" >> "${UPDFILE}"

echo "show" >> "${UPDFILE}"

if [[ "true" != "${SEND}" ]]; then
    echo "Not sending, SEND must be true!"
else
    echo "send" >> "${UPDFILE}"
fi

cat "${UPDFILE}" | nsupdate -k "${KEYFILE}"

rm "${UPDFILE}"

